spring:
  lifecycle:
    timeout-per-shutdown-phase: '30s'
  main:
    banner-mode: 'OFF'
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    show-details: always
  endpoint:
    health:
      probes:
        enabled: true
server:
  shutdown: graceful