server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    kubernetes:
      loadbalancer:
        enabled: false
      enabled: false
    gateway:
      routes:
        - predicates:
            - Path=/**
